""" added due date into the existing task table

Revision ID: b21d8d4f3162
Revises: f9df060fb82d
Create Date: 2026-03-10 17:10:15.099630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21d8d4f3162'
down_revision: Union[str, Sequence[str], None] = 'f9df060fb82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
